[package]
name = "ui_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.4.2", features = ["async-std"] }
iced_native = "0.5.1"
iced_futures = "0.4.1"
async-std = "1.9.0"